[build]
  command = "npm ci --include=dev && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Custom domain configuration
[context.production]
  command = "npm ci --include=dev && npm run build"
  publish = "dist"

# Specific configuration for custom domain
[context.production.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

# Force HTTPS and proper headers for custom domain
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets with proper headers
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Handle CSS files properly
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Handle JS files properly
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# Force HTTPS redirect
[[redirects]]
  from = "http://klyrosoft.com/*"
  to = "https://klyrosoft.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.klyrosoft.com/*"
  to = "https://klyrosoft.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.klyrosoft.com/*"
  to = "https://klyrosoft.com/:splat"
  status = 301
  force = true

# SPA fallback - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200